name: ftth
initialState: ACCOUNT_CREATION
transitions:
  - source: ACCOUNT_CREATION
    target: ACCOUNT_CREATION_1
    event: REG_STEP_1
  - source: ACCOUNT_CREATION_1
    target: ACCOUNT_CREATION_2
    event: REG_STEP_2
  - source: ACCOUNT_CREATION_2
    target: MOBILE_VERIFICATION
    event: REG_STEP_3
  - source: MOBILE_VERIFICATION
    target: INSTALLATION_SCHEDULE
    event: VERIFY_MOBILE