name: ftth
initialState: ACCOUNT_CREATION
transitions:
  - source: ACCOUNT_CREATION
    target: MOBILE_VERIFICATION
    event: CREATE_ACCOUNT
  - source: MOBILE_VERIFICATION
    target: CONTACT_COLLECTION
    event: VERIFY_MOBILE
  - source: CONTACT_COLLECTION
    target: COVERAGE_VERIFICATION
    event: ADD_CONTACT